# Generated by Django 4.0.2 on 2022-02-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MovieMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('m_desc', models.CharField(max_length=50, verbose_name='Movie Description')),
                ('m_image', models.ImageField(upload_to='pics/', verbose_name='Movie Image')),
            ],
            options={
                'unique_together': {('m_name', 'm_desc', 'm_image')},
            },
        ),
        migrations.CreateModel(
            name='SetMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=50, verbose_name='Show Time')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('price', models.IntegerField()),
                ('seats', models.CharField(default='', max_length=100)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviemaster')),
            ],
            options={
                'unique_together': {('active', 'show', 'start_time', 'end_time')},
            },
        ),
    ]
