# Generated by Django 4.0.2 on 2022-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemaster',
            name='m_desc',
            field=models.CharField(max_length=250, verbose_name='Movie Description'),
        ),
    ]
